spring.application.name=wms

spring.datasource.url=jdbc:postgresql://localhost:5432/db_wms
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.servlet.session.timeout=30m
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#.JWT
jwt.secret=secret-key-wms6h7g8f9d0s1a2d3f4g5h6j7k8l9z1x2c3v4b5n6m7e1w4a1
#jwt.expiration=86400000
