spring.application.name=wms

# ======================================================
# PRIMARY DATASOURCE (db_wms)
# ======================================================
spring.datasource.wms.jdbc-url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_wms}
spring.datasource.wms.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.wms.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.wms.driver-class-name=org.postgresql.Driver

# ======================================================
# AUDIT DATASOURCE (db_audit)
# ======================================================
spring.datasource.audit.jdbc-url=${SPRING_AUDIT_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_audit}
spring.datasource.audit.username=${SPRING_AUDIT_DATASOURCE_USERNAME:admin}
spring.datasource.audit.password=${SPRING_AUDIT_DATASOURCE_PASSWORD:password}
spring.datasource.audit.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.servlet.session.timeout=30m
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#.JWT
jwt.secret=secret-key-wms6h7g8f9d0s1a2d3f4g5h6j7k8l9z1x2c3v4b5n6m7e1w4a1
#jwt.expiration=86400000
